language: go

matrix:
  include:
  - go: "1.10.x"
    script:  go test -v ./...
  - go: "1.11.x"
    script: go test -v -mod=vendor ./...

env:
  - PATH=/home/travis/gopath/bin:$PATH GO111MODULE=on

install: true
